{% set name = "qcdloop" %}
{% set version = "2.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/scarrazza/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 75ac2d00231714210859d39c4beebce14f183707afe47f4550f33ef9f348b3c1
  folder: source
  patches:
    # Remove in releases after v2.1.0
    # c.f. https://github.com/scarrazza/qcdloop/pull/35
    - add-back-support-for-ppc64le.patch

build:
  # FIXME: clang does not yet support quadmath, so macOS builds are broken
  skip: true  # [not linux]
  number: 0
  run_exports:
    - {{ pin_subpackage('qcdloop', max_pin='x.x') }}
  script:
    # FIXME: Remove unknown argument: '-fext-numeric-literals' CMAKE_CXX_FLAGS for macOS builds
    # Note that conda-forge sed is gsed even on macOS
    - sed -i 's/ -fext-numeric-literals//g' source/CMakeLists.txt  # [osx]
    - cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DENABLE_EXAMPLES=ON -S source -B build
    - cmake -LH build
    - cmake --build build --clean-first --parallel="${CPU_COUNT}"
    - cmake --install build

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - sed  # [osx]
  run:
    - grep  # for qcdloop-config

test:
  source_files:
    - source/
  requires:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
  commands:
    - test -f $PREFIX/bin/qcdloop-config
    - test -f $PREFIX/lib/pkgconfig/qcdloop.pc
    - test -f $PREFIX/include/qcdloop/bubble.h
    - test -f $PREFIX/include/qcdloop/maths.h
    - test -f $PREFIX/include/qcdloop/types.h
    - test -f $PREFIX/include/qcdloop/config.h.in
    - test -f $PREFIX/include/qcdloop/timer.h
    - test -f $PREFIX/include/qcdloop/qcdloop.h
    - test -f $PREFIX/include/qcdloop/wrapper.h
    - test -f $PREFIX/include/qcdloop/cache.h
    - test -f $PREFIX/include/qcdloop/topology.h
    - test -f $PREFIX/include/qcdloop/triangle.h
    - test -f $PREFIX/include/qcdloop/tools.h
    - test -f $PREFIX/include/qcdloop/exceptions.h
    - test -f $PREFIX/include/qcdloop/tadpole.h
    - test -f $PREFIX/include/qcdloop/box.h
    - test -f $PREFIX/include/qcdloop/config.h
    - test -f $PREFIX/lib/libqcdloop${SHLIB_EXT}

    - qcdloop-config --help
    - qcdloop-config --prefix
    - qcdloop-config --incdir
    - qcdloop-config --libdir
    - qcdloop-config --cppflags
    - qcdloop-config --ldflags
    - qcdloop-config --version

    - cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DENABLE_EXAMPLES=ON -S source -B build
    - cmake --build build --clean-first --parallel="${CPU_COUNT}"
    - cd build
    - ./cache_test  # [build_platform == target_platform]
    - ./cmass_test  # [build_platform == target_platform]
    - ./trigger_test  # [build_platform == target_platform]

about:
  home: https://github.com/scarrazza/qcdloop
  summary: 'QCDLoop: an object-oriented one-loop scalar Feynman integrals framework'
  license: GPL-3.0-only
  license_family: GPL
  license_file: source/LICENSE
  doc_url: https://qcdloop.web.cern.ch/
  dev_url: https://github.com/scarrazza/qcdloop

extra:
  recipe-maintainers:
    - matthewfeickert
    - scarrazza
