{% set name = "qcdloop" %}
{% set version = "2.0.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/scarrazza/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6ffbd371658726054b903dce9a7855ac02b258eac59e2ee13524dda9e278f23b
  folder: source
  patches:
    # Avoid egrep warning breaking qcdloop-config
    - 0001-fix-Use-grep-E-over-egrep.patch
    # Allow setting CMAKE_CXX_FLAGS from CXXFLAGS
    - 0002-environment-override-of-CMAKE_CXX_FLAGS.patch
    # Give cmake_minimum_required a range of supported CMakes
    - 0003-support-range-of-cmakes.patch

build:
  # FIXME: clang does not yet support quadmath, so macOS builds are broken
  skip: true  # [win]
  number: 5
  run_exports:
    - {{ pin_subpackage('qcdloop', max_pin='x.x') }}
  script:
    # - curl -L https://raw.githubusercontent.com/gcc-mirror/gcc/f5a87c8d8c6a8cfcd23595e67d3b86939e01c75c/libquadmath/quadmath.h -o $BUILD_PREFIX/include/quadmath.h  # [osx]
    - cp $(find $BUILD_PREFIX -type f -iname "quadmath.h") $PREFIX/include/  # [osx]
    # FIXME: Remove unknown argument: '-fext-numeric-literals' CMAKE_CXX_FLAGS for macOS builds
    # Note that conda-forge sed is gsed even on macOS
    - sed -i 's/ -fext-numeric-literals//g' source/CMakeLists.txt  # [osx]
    - echo "Looking for quadmath.h"
    - echo "Looking under $BUILD_PREFIX"
    - find $BUILD_PREFIX -type f -iname "*quadmath*"
    - echo "Looking under $PREFIX"
    - find $PREFIX -type f -iname "*quadmath*"
    - cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DENABLE_EXAMPLES=ON -S source -B build
    - cmake -LH build
    - cmake --build build --clean-first --parallel="${CPU_COUNT}"
    - cmake --install build

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - sed  # [osx]
    # - curl # [osx]
  run:
    - grep  # for qcdloop-config

test:
  source_files:
    - build
  commands:
    - test -f $PREFIX/bin/qcdloop-config
    - test -f $PREFIX/lib/pkgconfig/qcdloop.pc
    - test -f $PREFIX/include/qcdloop/bubble.h
    - test -f $PREFIX/include/qcdloop/maths.h
    - test -f $PREFIX/include/qcdloop/types.h
    - test -f $PREFIX/include/qcdloop/config.h.in
    - test -f $PREFIX/include/qcdloop/timer.h
    - test -f $PREFIX/include/qcdloop/qcdloop.h
    - test -f $PREFIX/include/qcdloop/wrapper.h
    - test -f $PREFIX/include/qcdloop/cache.h
    - test -f $PREFIX/include/qcdloop/topology.h
    - test -f $PREFIX/include/qcdloop/triangle.h
    - test -f $PREFIX/include/qcdloop/tools.h
    - test -f $PREFIX/include/qcdloop/exceptions.h
    - test -f $PREFIX/include/qcdloop/tadpole.h
    - test -f $PREFIX/include/qcdloop/box.h
    - test -f $PREFIX/include/qcdloop/config.h
    - test -f $PREFIX/lib/libqcdloop${SHLIB_EXT}

    - qcdloop-config --help
    - qcdloop-config --prefix
    - qcdloop-config --incdir
    - qcdloop-config --libdir
    - qcdloop-config --cppflags
    - qcdloop-config --ldflags
    - qcdloop-config --version

    - cd build
    - ./cache_test  # [build_platform == target_platform]
    - ./cmass_test  # [build_platform == target_platform]
    - ./trigger_test  # [build_platform == target_platform]

about:
  home: https://github.com/scarrazza/qcdloop
  summary: 'QCDLoop: an object-oriented one-loop scalar Feynman integrals framework'
  license: GPL-3.0-only
  license_family: GPL
  license_file: source/LICENSE
  doc_url: https://qcdloop.web.cern.ch/
  dev_url: https://github.com/scarrazza/qcdloop

extra:
  recipe-maintainers:
    - matthewfeickert
    - scarrazza
